version: '3.9'
services:
  app:
    container_name: filas_app_container
    build: .
    command: './wait-for-it.sh filas_rabbitmq_container:15672 -s -- pm2-runtime ecosystem.config.js'
    environment:
      - NODE_ENV=docker.internal
      # - NODE_ENV=docker.network
    ports:
      - "7710:3000"
      - "7711:3001"
    networks:
      - entregamaisnetwork
    restart: on-failure

  rabbitmq:
    container_name: filas_rabbitmq_container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-data-setup:/setup
    tty: true
    environment:
      - RABBITMQ_DEFAULT_USER=ifpb
      - RABBITMQ_DEFAULT_PASS=ifpb
      - CLUSTERED=true
      - RABBITMQ_ERLANG_COOKIE=default_key
    networks:
      - entregamaisnetwork
    restart: unless-stopped

networks:
  entregamaisnetwork:
    name: entregamaisnetwork

volumes:
  rabbitmq-data:
  rabbitmq-data-setup:
